/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trenelectromagnetico;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elisabet Alvarez
 */
public class VentanaResgistros extends javax.swing.JFrame {

    /**
     * Creates new form VentanaResgistros
     */
    public void elementosEnTabla(ListaRegistro list){
        TableRegistros.setModel(list.modeloTabla((DefaultTableModel) TableRegistros.getModel()));
    }
    
    public VentanaResgistros() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableRegistros = new javax.swing.JTable();
        ButtonAtras = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        ButtonDetalles = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Responsable", "Nº de vueltas", "Fecha", "Vuelta más rápida", "Vuelta más lenta", "Promedio de pasajeros"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableRegistros);

        ButtonAtras.setText("Atrás");
        ButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAtrasActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo.setText("REGISTROS");

        ButtonDetalles.setText("Detalles");
        ButtonDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDetallesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonDetalles)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAtras)
                    .addComponent(ButtonDetalles))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableRegistrosMouseClicked
        if (evt.getClickCount() == 2) {
            System.out.println("double clicked");
            int columna = TableRegistros.getSelectedColumn();
            switch(columna){
                case 0:
                //Main.r1.ordenarCodigo();
                elementosEnTabla(Main.r1);
                break;
                case 2:
                Main.r1.ordenarResponsable();
                elementosEnTabla(Main.r1);
                break;
                case 3:
                Main.r1.ordenarVuelta();
                elementosEnTabla(Main.r1);
                break;
                case 4:
                Main.r1.ordenarVuerapida();
                elementosEnTabla(Main.r1);
                break;
                case 5:
                Main.r1.ordenarVuelenta();
                elementosEnTabla(Main.r1);
                break;
                case 6:
                Main.r1.ordenarPeso();
                elementosEnTabla(Main.r1);
                break;
                default:
                break;

            }

        }
    }//GEN-LAST:event_TableRegistrosMouseClicked

    private void ButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAtrasActionPerformed

    private void ButtonDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDetallesActionPerformed
       int fila = TableRegistros.getSelectedRow();
       Registro registro = Main.r1.buscarIndice(fila);
       VentanaVueltas vv= new VentanaVueltas();
       vv.setVisible(true);
       
    }//GEN-LAST:event_ButtonDetallesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaResgistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaResgistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaResgistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaResgistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaResgistros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAtras;
    private javax.swing.JToggleButton ButtonDetalles;
    private javax.swing.JTable TableRegistros;
    private javax.swing.JLabel Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
