/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trenelectromagnetico;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elisabet Alvarez
 */
public class VentanaVueltas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaVueltas
     */
    NodoRegistro registro;
    public void elementosEnTabla(){
        TableVueltas.setModel(registro.getDato().getListavuelta().modeloTabla((DefaultTableModel) TableVueltas.getModel()));
    }
    
    public VentanaVueltas() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public void recibirRegistro(NodoRegistro registro){
        this.registro= registro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableVueltas = new javax.swing.JTable();
        ButtonAtras = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableVueltas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Ruta", "Nº de Pasajeros", "Salida", "Llegada", "Duración", "Velocidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableVueltas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableVueltasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableVueltas);
        if (TableVueltas.getColumnModel().getColumnCount() > 0) {
            TableVueltas.getColumnModel().getColumn(0).setResizable(false);
            TableVueltas.getColumnModel().getColumn(1).setResizable(false);
            TableVueltas.getColumnModel().getColumn(2).setResizable(false);
            TableVueltas.getColumnModel().getColumn(3).setResizable(false);
            TableVueltas.getColumnModel().getColumn(4).setResizable(false);
            TableVueltas.getColumnModel().getColumn(5).setResizable(false);
            TableVueltas.getColumnModel().getColumn(6).setResizable(false);
        }

        ButtonAtras.setText("Atrás");
        ButtonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAtrasMouseClicked(evt);
            }
        });
        ButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAtrasActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo.setText("VUELTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(311, 311, 311)
                                .addComponent(Titulo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ButtonAtras)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAtrasActionPerformed

    private void TableVueltasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableVueltasMouseClicked
       if (evt.getClickCount() == 2) {
            System.out.println("double clicked");
            int columna = TableVueltas.getSelectedColumn();
            switch(columna){
                case 0:
                    registro.getDato().getListavuelta().ordenarCodigo();
                    elementosEnTabla();
                    break;
                case 2:
                    registro.getDato().getListavuelta().ordenarPasajeros();
                    elementosEnTabla();
                    break;
                case 3:
                    registro.getDato().getListavuelta().ordenarSalida();
                    elementosEnTabla();
                    break;
                case 4:
                    registro.getDato().getListavuelta().ordenarLlegada();
                    elementosEnTabla();
                    break;
                case 5:
                    registro.getDato().getListavuelta().ordenarTiempo();
                    elementosEnTabla();
                    break;
                case 6:
                    registro.getDato().getListavuelta().ordenarVelocidad();
                    elementosEnTabla();
                    break;
                default:
                    break;
                
            }
                
                    
        }
    }//GEN-LAST:event_TableVueltasMouseClicked

    private void ButtonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAtrasMouseClicked

        VentanaNuevoregistro vn = new VentanaNuevoregistro();
        vn.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonAtrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVueltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVueltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVueltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVueltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVueltas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAtras;
    private javax.swing.JTable TableVueltas;
    private javax.swing.JLabel Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
